#ifndef TERMINAL_H_INCLUDED
#define TERMINAL_H_INCLUDED
#endif

/*
* Conjunto de definições de Terminal
*/
#define TERMINAL_TAMANHODIRETORIO 128
#define TERMINAL_TAMANHOPATH 512
#define TERMINAL_TAMANHOUSUARIO 32
#define TERMINAL_NUMLINHAS 128
#define TERMINAL_TAMANHOLINHA 512
#define TERMINAL_TAMANHOPALAVRA 32
